# Site settings
name: 'Brittany Woods'
description: 'Brittany is an automator of the things, a DevOps practitioner, a speaker, a shade queen, and an animal lover.'
meta_description: 'Brittany Woods, automator, lover of tea, haver of opinions, shade queen'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://brittanynwoods.com/
cover_image: bc_1.png
# Add your GA Tracking Id
ga_analytics: UA-83670226-1


# Author
author:
  name: 'Brittany Woods'
  image: 'authorimage.jpg'
  greetings: "Hi! I'm Brittany"
  description: "I automate computer things. I love tea. I have opinions. I throw some shade on Twitter."
  bio: 'Brittany is an automator of the things, a DevOps practitioner, a speaker, a shade queen, and an animal lover.'

# Contact form setings
email: brittany.woods@hey.com
contact_page_description: "Have a question or want to get in touch? Feel free to reach out!"
thankyou_page_description: "Your message has been successfully sent. I will be in touch soon!"

# Social links
twitter: 'bnwoods2008'
facebook: 
github: 'bnwoods'
codepen: 
dribbble: 
medium: 
instagram:
pinterest: 
linkedin: 'https://linkedin.com/in/bnwoods'
producthunt: 

# Navigation
navigation:
  - text: About
    url: /about
  - text: Speaking
    url: /speaking
  - text: Around the Web
    url: /aroundtheweb
  - text: Consulting
    url: /consulting
  - text: Resume
    url: /resume
  - text: Contact Me
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
